const STATIONS = [
  {
    "id": 1,
    "name": "SITIO PUGO WS",
    "location": "SAN JUAN, ALFONSO LISTA, IFUGAO",
    "lat": 16.883048,
    "lon": 121.54267,
    "fund": "CCAW 2018",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 2,
    "name": "CULING WS",
    "location": "CULING WEST, CABATUAN, ISABELA",
    "lat": 16.944308,
    "lon": 121.64641,
    "fund": "CCAW 2018",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OFFLINE",
    "remarks": "FOR TROUBLESHOOTING",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 3,
    "name": "CENTRO LUNA WS",
    "location": "LUNA, ISABELA",
    "lat": 16.968058,
    "lon": 121.729096,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 4,
    "name": "OLD CENTRO WS",
    "location": "OLD CENTRO 1, SAN MATEO, ISABELA",
    "lat": 16.888997,
    "lon": 121.566542,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 5,
    "name": "RANG-AY WS",
    "location": "RANG-AY, CABATUAN, ISABELA",
    "lat": 16.921879,
    "lon": 121.61357,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 6,
    "name": "MALLALATANG GRANDE WS",
    "location": "MALALATANG GRANDE, REINA MERCEDES, ISABELA",
    "lat": 17.012242,
    "lon": 121.796438,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 7,
    "name": "BAGONG SIKAT WS",
    "location": "BAGONG SIKAT, SAN MATEO, ISABELA",
    "lat": 16.922879,
    "lon": 121.570342,
    "fund": "COB 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "APRIL 28, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 8,
    "name": "LALOG WS",
    "location": "LALOG, LUNA, ISABELA",
    "lat": 16.987404,
    "lon": 121.718822,
    "fund": "COB 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "APRIL 28, 2027",
    "status": "OPERATIONAL",
    "remarks": "DEFECTIVE LCD DISPLAY",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 9,
    "name": "CENTRO AURORA WS",
    "location": "AURORA, ISABELA",
    "lat": 16.99014,
    "lon": 121.635765,
    "fund": "COB 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "APRIL 28, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 10,
    "name": "LENZON WS",
    "location": "LENZON, GAMU, ISABELA",
    "lat": 17.033564,
    "lon": 121.814258,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 11,
    "name": "BANQUERO WS",
    "location": "BANQUERO, REINA MERCEDES, ISABELA",
    "lat": 17.022787,
    "lon": 121.777931,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OFFLINE",
    "remarks": "FOR TROUBLESHOOTING",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 12,
    "name": "SINAMAR WS",
    "location": "SINAMAR NORTE,SAN MATEO, ISABELA",
    "lat": 16.844348,
    "lon": 121.544921,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 13,
    "name": "CENTRO CABATUAN WS",
    "location": "CABATUAN, ISABELA",
    "lat": 16.952856,
    "lon": 121.669339,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 14,
    "name": "CALUPAAN WS",
    "location": "CALUPAAN, ALFONSO LISTA, IFUGAO",
    "lat": 16.857072,
    "lon": 121.525898,
    "fund": "CCAW 2022",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "JANUARY 2, 2027",
    "status": "OFFLINE",
    "remarks": "FOR TROUBLESHOOTING",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 15,
    "name": "VICTORIA WS",
    "location": "VICTORIA, AURORA, ISABELA",
    "lat": 16.986346,
    "lon": 121.666227,
    "fund": "CCAW 2022",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "JANUARY 2, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 16,
    "name": "SALUCONG WS",
    "location": "SALUCONG, REINA MERCEDES, ISABELA",
    "lat": 17.026917,
    "lon": 121.742992,
    "fund": "CCAW 2022",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "JANUARY 2, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 17,
    "name": "NAGUILIAN WS",
    "location": "NAGUILIAN, ISABELA",
    "lat": 17.023018,
    "lon": 121.835666,
    "fund": "CCAW 2018",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 18,
    "name": "BELLALUZ WS",
    "location": "BELLA LUZ, SAN MATEO, ISABELA",
    "lat": 16.869351,
    "lon": 121.544533,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 19,
    "name": "APIAT WS",
    "location": "APIAT, AURORA, ISABELA",
    "lat": 16.954072,
    "lon": 121.602062,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 20,
    "name": "SAN ISIDRO WS",
    "location": "SAN ISIDRO, LUNA, ISABELA",
    "lat": 17.005395,
    "lon": 121.71978,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 21,
    "name": "PAGRANGAYAN WS",
    "location": "PAGRANGAYAN, RAMON, ISABELA",
    "lat": 16.757821,
    "lon": 121.492619,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 22,
    "name": "GAMU WS",
    "location": "GAMU, ISABELA",
    "lat": 17.047378,
    "lon": 121.834136,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 23,
    "name": "AURORA COMBINED WLRG",
    "location": "AURORA, ISABELA",
    "lat": 16.9711611,
    "lon": 121.6576694,
    "fund": "CCAW 2018",
    "type": "COMBINED WL & RG-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 24,
    "name": "GAMU COMBINED WLRG",
    "location": "GAMU, ISABELA",
    "lat": 17.0696694,
    "lon": 121.8428083,
    "fund": "CCAW 2018",
    "type": "COMBINED WL & RG-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 25,
    "name": "TAO-TAO COMBINED WLRG",
    "location": "ALFONSO LISTA, IFUGAO",
    "lat": 16.949696,
    "lon": 121.561095,
    "fund": "COB 2020",
    "type": "COMBINED WL & RG - SMS",
    "telemetry": "SHORT MESSAGE SERVICE",
    "subscription": "JUNE 30, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 26,
    "name": "AGLIPAY AWS",
    "location": "AGLIPAY, QUIRINO",
    "lat": 16.463112,
    "lon": 121.618344,
    "fund": "COB 2022",
    "type": "AWS-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 27,
    "name": "MADDELA AWS",
    "location": "MADDELA, QUIRINO",
    "lat": 16.3363167,
    "lon": 121.6792194,
    "fund": "COB 2022",
    "type": "AWS-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 28,
    "name": "NAGTIPUNAN AWS",
    "location": "NAGTIPUNAN, QUIRINO",
    "lat": 16.223462,
    "lon": 121.60688,
    "fund": "COB 2022",
    "type": "AWS-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam",
    "region": "",
    "systemArea": "MARIIS",
    "source": "Existing verified MARIIS inventory dataset"
  },
  {
    "id": 29,
    "name": "AGNO RIS • Rain Gauge",
    "location": "San Roque, San Manuel, Pangasinan",
    "lat": 16.11452777777778,
    "lon": 120.69377777777778,
    "fund": "Year Acquired: 2015",
    "type": "Rain Gauge",
    "telemetry": "By Subscription",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "Functional but due to high subscription cost per year, this office was not able to renew its subscription as of this period.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan",
    "system": "AGNO RIS",
    "yearAcquired": 2015,
    "contractor": "RCNC Enterprises",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 30,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "San Manuel, Pangasinan (Tambo)",
    "lat": 16.097952777777778,
    "lon": 120.68384444444445,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "The VHF Radio Telemetry System installed at Agno RIS is no longer operational. The equipment was damaged during the demolition of the old office building and the construction of the new National Irrigation Administration Region I Building in 2024.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Tambo)",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 31,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "San Manuel, Pangasinan (Rodriguez)",
    "lat": 16.071030555555556,
    "lon": 120.67670000000001,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "The VHF Radio Telemetry System installed at Agno RIS is no longer operational. The equipment was damaged during the demolition of the old office building and the construction of the new National Irrigation Administration Region I Building in 2024.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Rodriguez)",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 32,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "San Manuel, Pangasinan (Escitor)",
    "lat": 16.06067777777778,
    "lon": 120.66879444444444,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "The VHF Radio Telemetry System installed at Agno RIS is no longer operational. The equipment was damaged during the demolition of the old office building and the construction of the new National Irrigation Administration Region I Building in 2024.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Escitor)",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 33,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "Asingan, Pangasinan (Dayag)",
    "lat": 16.03536111111111,
    "lon": 120.66064444444444,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "During the construction phase, satellite components and other essential parts of the telemetry system were removed, resulting in the system becoming completely inoperative.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Dayag)",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 34,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "Asingan, Pangasinan (Manaols)",
    "lat": 16.01371111111111,
    "lon": 120.62297222222222,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "During the construction phase, satellite components and other essential parts of the telemetry system were removed, resulting in the system becoming completely inoperative.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Manaols)",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 35,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "Laoac, Pangasinan (Dado)",
    "lat": 16.006608333333332,
    "lon": 120.55155555555555,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "During the construction phase, satellite components and other essential parts of the telemetry system were removed, resulting in the system becoming completely inoperative.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Dado)",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 36,
    "name": "AGNO RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "Manaoag, Pangasinan",
    "lat": 16.001838888888887,
    "lon": 120.53596944444445,
    "fund": "Year Acquired: 2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "During the construction phase, satellite components and other essential parts of the telemetry system were removed, resulting in the system becoming completely inoperative.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan",
    "system": "AGNO RIS",
    "yearAcquired": 2020,
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 37,
    "name": "AGNO RIS • Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "location": "San Manuel, Pangasinan (Intake)",
    "lat": 16.114972222222224,
    "lon": 120.69395277777778,
    "fund": "Year Acquired: 2022",
    "type": "Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "telemetry": "By Subscription",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Intake)",
    "system": "AGNO RIS",
    "yearAcquired": 2022,
    "contractor": "JPLC Trading/Phil Instruments Corporation",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 38,
    "name": "AGNO RIS • Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "location": "San Manuel, Pangasinan (MGC)",
    "lat": 16.065822222222224,
    "lon": 120.67774166666668,
    "fund": "Year Acquired: 2022",
    "type": "Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "telemetry": "By Subscription",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (MGC)",
    "system": "AGNO RIS",
    "yearAcquired": 2022,
    "contractor": "JPLC Trading/Phil Instruments Corporation",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 39,
    "name": "AGNO RIS • Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "location": "Asingan, Pangasinan (LAT.F)",
    "lat": 16.01491111111111,
    "lon": 120.63999444444445,
    "fund": "Year Acquired: 2022",
    "type": "Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "telemetry": "By Subscription",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (LAT.F)",
    "system": "AGNO RIS",
    "yearAcquired": 2022,
    "contractor": "JPLC Trading/Phil Instruments Corporation",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 40,
    "name": "AGNO RIS • Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "location": "Laoac, Pangasinan (Yatyat)",
    "lat": 16.006055555555555,
    "lon": 120.55325555555555,
    "fund": "Year Acquired: 2022",
    "type": "Telemetry Water Level Sensor and Rain Gauge with Data Monitoring",
    "telemetry": "By Subscription",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan (Yatyat)",
    "system": "AGNO RIS",
    "yearAcquired": 2022,
    "contractor": "JPLC Trading/Phil Instruments Corporation",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 41,
    "name": "Sinocalan RIS • Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "location": "Sta. Barbara, Pangasinan",
    "lat": 15.998641666666666,
    "lon": 120.41284722222223,
    "fund": "Year Acquired: 2017/2020",
    "type": "Satellite Telemetry Water Level Sensor w/ Data Monitoring",
    "telemetry": "VHF Radio",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "Satellite units and other critical parts were removed during the construction period, and the telemetry system was not restored thereafter. The telemetry facilities at Sinocalan RIS remain inoperative.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Pangasinan",
    "system": "Sinocalan RIS",
    "yearAcquired": "2017/2020",
    "contractor": "Anascom Electronics and Supply Company",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 42,
    "name": "Amburayan RIS • Ultrasonic Water Level Sensor",
    "location": "Sudipen, La Union",
    "lat": 16.9086869,
    "lon": 120.4709705,
    "fund": "Year Acquired: 2022",
    "type": "Ultrasonic Water Level Sensor",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Amburayan RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 43,
    "name": "Amburayan RIS • Tipping Bucket Rain Gauge",
    "location": "Sudipen, La Union",
    "lat": 16.9086869,
    "lon": 120.4709705,
    "fund": "Year Acquired: 2022",
    "type": "Tipping Bucket Rain Gauge",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Amburayan RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 44,
    "name": "Amburayan RIS • Ultrasonic Water Level Sensor",
    "location": "Balaoan, La Union",
    "lat": 16.8366183,
    "lon": 120.4286456,
    "fund": "Year Acquired: 2022",
    "type": "Ultrasonic Water Level Sensor",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Amburayan RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 45,
    "name": "Amburayan RIS • Tipping Bucket Rain Gauge",
    "location": "Balaoan, La Union",
    "lat": 16.8366183,
    "lon": 120.4286456,
    "fund": "Year Acquired: 2022",
    "type": "Tipping Bucket Rain Gauge",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Amburayan RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 46,
    "name": "Amburayan RIS • Rain Gauge",
    "location": "Sudipen, La Union",
    "lat": 16.9008139,
    "lon": 120.4539194,
    "fund": "Year Acquired: 2015",
    "type": "Rain Gauge",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "The rain gauge subscription was in place during the JICA project period. The contract expired in 2017 and was not renewed because of the high cost. Following a period of non-use, the equipment is now no longer serviceable.",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Amburayan RIS",
    "yearAcquired": 2015,
    "contractor": "Global Waters",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 47,
    "name": "Masalip RIS • Ultrasonic Water Level Sensor",
    "location": "Agoo, La Union",
    "lat": 16.3307541,
    "lon": 120.3776702,
    "fund": "Year Acquired: 2022",
    "type": "Ultrasonic Water Level Sensor",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Masalip RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 48,
    "name": "Masalip RIS • Tipping Bucket Rain Gauge",
    "location": "Agoo, La Union",
    "lat": 16.3307541,
    "lon": 120.3776702,
    "fund": "Year Acquired: 2022",
    "type": "Tipping Bucket Rain Gauge",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "La Union",
    "system": "Masalip RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 49,
    "name": "Sta. Maria - Burgos RIS • Rain Gauge",
    "location": "Sta. Maria, Ilocos Sur",
    "lat": 17.363992,
    "lon": 120.472981,
    "fund": "Year Acquired: 2015",
    "type": "Rain Gauge",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "Subscription expired",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Sur",
    "system": "Sta. Maria - Burgos RIS",
    "yearAcquired": 2015,
    "contractor": "RCNC Enterprise",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 50,
    "name": "Bonga Pump # 2 PIS • Rain gauge",
    "location": "San Nicolas, Ilocos Norte",
    "lat": 18.121502777777778,
    "lon": 120.57673333333332,
    "fund": "Year Acquired: 2015",
    "type": "Rain gauge",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Bonga Pump # 2 PIS",
    "yearAcquired": 2015,
    "contractor": "RCNC Enterprise",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 51,
    "name": "Laoag-Vintar RIS • Rain gauge",
    "location": "Vintar, Ilocos Norte",
    "lat": 18.254016666666665,
    "lon": 120.68582777777779,
    "fund": "Year Acquired: 2018",
    "type": "Rain gauge",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "Subscription not renewed",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Laoag-Vintar RIS",
    "yearAcquired": 2018,
    "contractor": "ACDO Commercial & Industrial Supply",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 52,
    "name": "Laoag-Vintar RIS • River Gauge",
    "location": "Vintar, Ilocos Norte",
    "lat": 18.254016666666665,
    "lon": 120.68582777777779,
    "fund": "Year Acquired: 2018",
    "type": "River Gauge",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "Subscription not renewed/Damaged sensor",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Laoag-Vintar RIS",
    "yearAcquired": 2018,
    "contractor": "ACDO Commercial & Industrial Supply",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 53,
    "name": "Laoag-Vintar RIS • Public Address System Console with Siren",
    "location": "Vintar, Ilocos Norte",
    "lat": 18.254016666666665,
    "lon": 120.68582777777779,
    "fund": "Year Acquired: 2018",
    "type": "Public Address System Console with Siren",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "NON-OPERATIONAL",
    "remarks": "Damaged tipping bucket mechanism",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Laoag-Vintar RIS",
    "yearAcquired": 2018,
    "contractor": "ACDO Commercial & Industrial Supply",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 54,
    "name": "Dingras RIS • Rain gauge",
    "location": "Marcos, Ilocos Norte",
    "lat": 18.01910833333333,
    "lon": 120.67288055555557,
    "fund": "Year Acquired: 2018",
    "type": "Rain gauge",
    "telemetry": "Satellite",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Dingras RIS",
    "yearAcquired": 2018,
    "contractor": "BP Integrated Technologies Inc",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 55,
    "name": "Solsona RIS • Rain gauge",
    "location": "Solsona, Ilocos Norte",
    "lat": 18.098769444444443,
    "lon": 120.77330833333333,
    "fund": "Year Acquired: 2022",
    "type": "Rain gauge",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Solsona RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  },
  {
    "id": 56,
    "name": "Bolo RIS • Rain gauge/River gauge",
    "location": "Dumalneg, Ilocos Norte",
    "lat": 18.529083333333332,
    "lon": 120.83590277777778,
    "fund": "Year Acquired: 2022",
    "type": "Rain gauge/River gauge",
    "telemetry": "SMS",
    "subscription": "",
    "status": "OPERATIONAL",
    "remarks": "Functional",
    "area": "Region I",
    "region": "Region I",
    "systemArea": "Region I",
    "division": "Ilocos Norte",
    "system": "Bolo RIS",
    "yearAcquired": 2022,
    "contractor": "Philinstruments Corp.",
    "source": "NIA Region I Inventory of Existing Telemetry Systems (supplied images)"
  }
];
