const STATIONS = [
  {
    "id": 1,
    "name": "SITIO PUGO WS",
    "location": "SAN JUAN, ALFONSO LISTA, IFUGAO",
    "lat": 16.883048,
    "lon": 121.54267,
    "fund": "CCAW 2018",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 2,
    "name": "CULING WS",
    "location": "CULING WEST, CABATUAN, ISABELA",
    "lat": 16.944308,
    "lon": 121.64641,
    "fund": "CCAW 2018",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OFFLINE",
    "remarks": "FOR TROUBLESHOOTING",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 3,
    "name": "CENTRO LUNA WS",
    "location": "LUNA, ISABELA",
    "lat": 16.968058,
    "lon": 121.729096,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 4,
    "name": "OLD CENTRO WS",
    "location": "OLD CENTRO 1, SAN MATEO, ISABELA",
    "lat": 16.888997,
    "lon": 121.566542,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 5,
    "name": "RANG-AY WS",
    "location": "RANG-AY, CABATUAN, ISABELA",
    "lat": 16.921879,
    "lon": 121.61357,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 6,
    "name": "MALLALATANG GRANDE WS",
    "location": "MALALATANG GRANDE, REINA MERCEDES, ISABELA",
    "lat": 17.012242,
    "lon": 121.796438,
    "fund": "COB 2019",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 7,
    "name": "BAGONG SIKAT WS",
    "location": "BAGONG SIKAT, SAN MATEO, ISABELA",
    "lat": 16.922879,
    "lon": 121.570342,
    "fund": "COB 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "APRIL 28, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 8,
    "name": "LALOG WS",
    "location": "LALOG, LUNA, ISABELA",
    "lat": 16.987404,
    "lon": 121.718822,
    "fund": "COB 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "APRIL 28, 2027",
    "status": "OPERATIONAL",
    "remarks": "DEFECTIVE LCD DISPLAY",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 9,
    "name": "CENTRO AURORA WS",
    "location": "AURORA, ISABELA",
    "lat": 16.99014,
    "lon": 121.635765,
    "fund": "COB 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "APRIL 28, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 10,
    "name": "LENZON WS",
    "location": "LENZON, GAMU, ISABELA",
    "lat": 17.033564,
    "lon": 121.814258,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 11,
    "name": "BANQUERO WS",
    "location": "BANQUERO, REINA MERCEDES, ISABELA",
    "lat": 17.022787,
    "lon": 121.777931,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OFFLINE",
    "remarks": "FOR TROUBLESHOOTING",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 12,
    "name": "SINAMAR WS",
    "location": "SINAMAR NORTE,SAN MATEO, ISABELA",
    "lat": 16.844348,
    "lon": 121.544921,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 13,
    "name": "CENTRO CABATUAN WS",
    "location": "CABATUAN, ISABELA",
    "lat": 16.952856,
    "lon": 121.669339,
    "fund": "CCAW 2021",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "SEPTEMBER 21, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 14,
    "name": "CALUPAAN WS",
    "location": "CALUPAAN, ALFONSO LISTA, IFUGAO",
    "lat": 16.857072,
    "lon": 121.525898,
    "fund": "CCAW 2022",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "JANUARY 2, 2027",
    "status": "OFFLINE",
    "remarks": "FOR TROUBLESHOOTING",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 15,
    "name": "VICTORIA WS",
    "location": "VICTORIA, AURORA, ISABELA",
    "lat": 16.986346,
    "lon": 121.666227,
    "fund": "CCAW 2022",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "JANUARY 2, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 16,
    "name": "SALUCONG WS",
    "location": "SALUCONG, REINA MERCEDES, ISABELA",
    "lat": 17.026917,
    "lon": 121.742992,
    "fund": "CCAW 2022",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "JANUARY 2, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 17,
    "name": "NAGUILIAN WS",
    "location": "NAGUILIAN, ISABELA",
    "lat": 17.023018,
    "lon": 121.835666,
    "fund": "CCAW 2018",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "AUGUST 23, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 18,
    "name": "BELLALUZ WS",
    "location": "BELLA LUZ, SAN MATEO, ISABELA",
    "lat": 16.869351,
    "lon": 121.544533,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 19,
    "name": "APIAT WS",
    "location": "APIAT, AURORA, ISABELA",
    "lat": 16.954072,
    "lon": 121.602062,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 20,
    "name": "SAN ISIDRO WS",
    "location": "SAN ISIDRO, LUNA, ISABELA",
    "lat": 17.005395,
    "lon": 121.71978,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 21,
    "name": "PAGRANGAYAN WS",
    "location": "PAGRANGAYAN, RAMON, ISABELA",
    "lat": 16.757821,
    "lon": 121.492619,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 22,
    "name": "GAMU WS",
    "location": "GAMU, ISABELA",
    "lat": 17.047378,
    "lon": 121.834136,
    "fund": "COB 2024",
    "type": "SIRCOM WARNING",
    "telemetry": "VHF RADIO",
    "subscription": "MAY 6, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 23,
    "name": "AURORA COMBINED WLRG",
    "location": "AURORA, ISABELA",
    "lat": 16.9711611,
    "lon": 121.6576694,
    "fund": "CCAW 2018",
    "type": "COMBINED WL & RG-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 24,
    "name": "GAMU COMBINED WLRG",
    "location": "GAMU, ISABELA",
    "lat": 17.0696694,
    "lon": 121.8428083,
    "fund": "CCAW 2018",
    "type": "COMBINED WL & RG-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 25,
    "name": "TAO-TAO COMBINED WLRG",
    "location": "ALFONSO LISTA, IFUGAO",
    "lat": 16.949696,
    "lon": 121.561095,
    "fund": "COB 2020",
    "type": "COMBINED WL & RG - SMS",
    "telemetry": "SHORT MESSAGE SERVICE",
    "subscription": "JUNE 30, 2027",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 26,
    "name": "AGLIPAY AWS",
    "location": "AGLIPAY, QUIRINO",
    "lat": 16.463112,
    "lon": 121.618344,
    "fund": "COB 2022",
    "type": "AWS-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 27,
    "name": "MADDELA AWS",
    "location": "MADDELA, QUIRINO",
    "lat": 16.3363167,
    "lon": 121.6792194,
    "fund": "COB 2022",
    "type": "AWS-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  },
  {
    "id": 28,
    "name": "NAGTIPUNAN AWS",
    "location": "NAGTIPUNAN, QUIRINO",
    "lat": 16.223462,
    "lon": 121.60688,
    "fund": "COB 2022",
    "type": "AWS-CLOUD BASE",
    "telemetry": "POCKET-BASED TELEPHONY",
    "subscription": "DECEMBER 19, 2026",
    "status": "OPERATIONAL",
    "remarks": "GOOD WORKING CONDITION",
    "area": "Downstream of Magat Dam"
  }
];